apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
  namespace: airflow
data:
  # Конфигурация Airflow
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
  AIRFLOW__OPERATORS__DEFAULT_QUEUE: "default"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "5"
  

  # Конфигурация Kubernetes Executor
  AIRFLOW__KUBERNETES_EXECUTOR__NAMESPACE: "airflow"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_REPOSITORY: "apache/airflow"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_CONTAINER_TAG: "2.10.2-python3.9"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS: "True"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_SUCCESS: "True"
  AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS_ON_FAILURE: "False"
  
  # Database Configuration  
  POSTGRES_DB: "airflow"
  POSTGRES_USER: "airflow"
  
  # Версии Python и Airflow
  PYTHON_VERSION: "3.11"
  APACHE_AIRFLOW_VERSION: "2.10.2"

  # Webserver admin
  WEBSERVER_ADMIN_LOGIN: "admin"
  WEBSERVER_ADMIN_EMAIL: "admin@example.com"

  # Уровень логирования - добавляем недостающие переменные
  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
  AIRFLOW__CORE__LOGGING_LEVEL: "INFO"
  AIRFLOW__LOGGING__CELERY_LOGGING_LEVEL: "INFO"
  AIRFLOW__LOGGING__FAB_LOGGING_LEVEL: "WARN"
  AIRFLOW__LOGGING__FLASK_APPBUILDER_LOGGING_LEVEL: "WARN"
  AIRFLOW__LOGGING__PROCESSOR_LOG_LEVEL: "INFO"
  AIRFLOW__KUBERNETES_EXECUTOR__WORKER_PODS_CREATION_BATCH_SIZE: "1"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
  AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: "/opt/airflow/logs/dag_processor_manager/dag_processor_manager.log"
  AIRFLOW__LOGGING__COLORED_CONSOLE_LOG: "False"
  AIRFLOW__LOGGING__REMOTE_LOGGING: "False"
  
  # Дополнительные настройки для worker подов
  AIRFLOW__CORE__DAGS_FOLDER: "/opt/airflow/dags"
  AIRFLOW__CORE__BASE_LOG_FOLDER: "/opt/airflow/logs"
  AIRFLOW__CORE__PLUGINS_FOLDER: "/opt/airflow/plugins"

  # Настройки для worker подов
  AIRFLOW__KUBERNETES_EXECUTOR__ENV_FROM_CONFIGMAP_REF: "airflow-config"
  AIRFLOW__KUBERNETES_EXECUTOR__ENV_FROM_SECRET_REF: "airflow-secrets"

  # База данных для worker подов
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"