apiVersion: v1
kind: ConfigMap
metadata:
  name: worker-pod-template
  namespace: airflow
data:
  pod_template.yaml: |
    apiVersion: v1
    kind: Pod
    spec:
      serviceAccountName: airflow
      restartPolicy: Never
      containers:
      - name: base
        image: apache/airflow:slim-2.10.2-python3.9
        env:
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql+psycopg2://airflow:airflow@postgres:5432/airflow"
        - name: AIRFLOW__CORE__EXECUTOR
          value: "KubernetesExecutor"
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: "/opt/airflow/dags"
        - name: AIRFLOW__CORE__LOAD_EXAMPLES
          value: "False"
        volumeMounts:
        - name: dags-volume
          mountPath: /opt/airflow/dags
        - name: logs-volume
          mountPath: /opt/airflow/logs
        envFrom:
        - configMapRef:
            name: airflow-config
        - secretRef:
            name: airflow-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: dags-volume
        persistentVolumeClaim:
          claimName: airflow-dags-pvc
      - name: logs-volume
        persistentVolumeClaim:
          claimName: airflow-logs-pvc
